version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing Python dependencies
      - mkdir -p build/search_photos
      - mkdir -p build/index_photos
      - pip install -r otherscripts/requirements.txt -t build/search_photos/
      - pip install -r otherscripts/requirements.txt -t build/index_photos/

  pre_build:
    commands:
      - echo Preparing the packages
      - cp lambda_functions/search_photos.py build/search_photos/lambda_function.py
      - cp lambda_functions/index_photos.py build/index_photos/lambda_function.py

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Lambda packages
      - cd build/search_photos
      - zip -r ../../search_photos.zip .
      - cd ../index_photos
      - zip -r ../../index_photos.zip .

  post_build:
    commands:
      - echo Deploying Lambda functions
      - cd $CODEBUILD_SRC_DIR
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search_photos.zip
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index_photos.zip

artifacts:
  files:
    - search_photos.zip
    - index_photos.zip
